### ISSUE TITLE
"read-regex already refers to: #'clojure.tools.reader.impl.commons/read-regex"

### ISSUE THREAD

**Issue by m-r-hunt** [aiba/lein-count#4]
I got this problem when attempting to run the plugin.

clojure.lang.Compiler$CompilerException: java.lang.IllegalStateException: read-regex already refers to: #'clojure.tools.reader.impl.commons/read-regex in namespace: aiba.lein-count.constant-wrapping-reader, compiling:(aiba/lein_count/constant_wrapping_reader.clj:134:1)

Looks like a dependency issue that could be solved by not using :refer :all. Not sure why I've hit this problem when others haven't.

**Comment by aiba** [comment]
This seems related to #1 - For some reason in your case, lein-count is being run with an older version of tools.reader.

Is there any way you could help me reproduce this problem on my computer so I can debug it?

**Comment by m-r-hunt** [comment]
I fixed this upgrading my version of lein (it was quite old, as I don't think I'd ever bothered to upgrade). Lein itself must have been pulling in an old tools.reader.

I've got a new fun problem though:
```
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 17
^E:\clojurestuff\od117-walker/
                 ^
 at java.util.regex.Pattern.error (Pattern.java:1955)
    java.util.regex.Pattern.escape (Pattern.java:2471)
    java.util.regex.Pattern.atom (Pattern.java:2198)
    java.util.regex.Pattern.sequence (Pattern.java:2130)
    java.util.regex.Pattern.expr (Pattern.java:1996)
    java.util.regex.Pattern.compile (Pattern.java:1696)
    java.util.regex.Pattern.<init> (Pattern.java:1351)
    java.util.regex.Pattern.compile (Pattern.java:1028)
    clojure.core$re_pattern.invokeStatic (core.clj:4665)
    clojure.core$re_pattern.invoke (core.clj:4657)
    aiba.lein_count.core$relative_path_str.invokeStatic (core.clj:26)
    aiba.lein_count.core$relative_path_str.invoke (core.clj:20)
    leiningen.count$count$fn__1671.invoke (count.clj:66)
    clojure.core$map$fn__4785.invoke (core.clj:2644)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:521)
    clojure.core$seq__4357.invokeStatic (core.clj:137)
    clojure.core$print_sequential.invokeStatic (core_print.clj:46)
    clojure.core$fn__6072.invokeStatic (core_print.clj:153)
    clojure.core/fn (core_print.clj:153)
    clojure.lang.MultiFn.invoke (MultiFn.java:233)
    clojure.core$pr_on.invokeStatic (core.clj:3572)
    clojure.core$pr.invokeStatic (core.clj:3575)
    clojure.core$pr.invoke (core.clj:3575)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$pr_str.invokeStatic (core.clj:4580)
    clojure.core$pr_str.doInvoke (core.clj:4580)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    leiningen.count$count.invokeStatic (count.clj:66)
    leiningen.count$count.doInvoke (count.clj:47)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__5932.doInvoke (main.clj:272)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:322)
    leiningen.core.main$apply_task.invoke (main.clj:308)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
    leiningen.core.main$_main$fn__5998.invoke (main.clj:401)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```
Looks like a windows path issue, probably need to escape the backslashes somewhere.

**Comment by m-r-hunt** [comment]
Ahh, sorry, the backslash problem has been fixed in 1.0.4 which I didn't notice has been released since my original comment. My bad. Works for me now.

**Comment by exupero** [comment]
I'm having the same problem on one project, but not other, both using Lein 2.7.1 on the same machine. I've added exclusions for `org.clojure/tools.reader` to all plugins and project dependencies except `lein-count`, but I still get the error.

**Comment by aiba** [comment]
@exupero can you post a minimal project.clj that is causing the error?

**Comment by exupero** [comment]
The problem turns out to be the plugin lein-gorilla. `lein deps :plugin-tree` lists lein-gorilla, but not tools.reader as a sub-dependency. However, if I add `:exclusions [org.clojure/tools.reader]` to lein-gorilla in project.clj, the error disappears.
